# Generated by Django 5.1.1 on 2024-10-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'permissions': [('can_approve_loan', 'Can approve loan request'), ('can_reject_loan', 'Can reject loan request')]},
        ),
    ]
