services:
  web:
    build:
      context: .
      # target: builder
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
