services:
  web:
    build:
      context: .
      # target: builder
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}

      - SIGNING_KEY=${SIGNING_KEY}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME}
      - ROTATE_REFRESH_TOKENS=${ROTATE_REFRESH_TOKENS}
      - BLACKLIST_AFTER_ROTATION=${BLACKLIST_AFTER_ROTATION}
      - UPDATE_LAST_LOGIN=${UPDATE_LAST_LOGIN}
      - ALGORITHM=${ALGORITHM}
