services:
  web:
    build:
      context: .
      # target: builder
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    # command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DEBUG=${DEBUG}

      - SIGNING_KEY=${SIGNING_KEY}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME}
      - ROTATE_REFRESH_TOKENS=${ROTATE_REFRESH_TOKENS}
      - BLACKLIST_AFTER_ROTATION=${BLACKLIST_AFTER_ROTATION}
      - UPDATE_LAST_LOGIN=${UPDATE_LAST_LOGIN}
      - ALGORITHM=${ALGORITHM}
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate --noinput &&
             python3 manage.py collectstatic --noinput &&
             gunicorn --bind :8000 --workers 2 -k uvicorn.workers.UvicornWorker treyd.asgi:application"
